site_name: "Network DNA"
docs_dir: docs
# Remove explicit nav so MkDocs auto-generates navigation from the docs/ structure and page H1s

theme:
  name: hacker
  logo: networkdna_logo.jpg

repo_url: https://github.com/mjh2901/mkdocs_wikidna
edit_uri: edit/main/docs/

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji
  - pymdownx.superfences

